In [1]:
import numpy as np
import pandas as pd

from ecg_waveform.config import load_yaml
from ecg_waveform.core import Fiducials
from ecg_waveform.data import FiducialMapper, WFDBLoader
from ecg_waveform.detection import build_detector
from ecg_waveform.evaluation import compute_metrics
from ecg_waveform.signal.preprocessing import Preprocessor

preprocessor_config = load_yaml("preprocessing/preprocessing_pipeline.yaml")
preprocessor = Preprocessor.from_config(preprocessor_config)

mapper = FiducialMapper.from_yaml("mapper/annotation_labels.yaml")

loader = WFDBLoader("mitdb", annotation_extension="atr", symbol_mapper=mapper)

In [2]:
detector = build_detector("pan_tompkins_plus_plus")

results = []
for record_name in loader.list_records():
    record = loader[record_name]
    signal = record.get_signal(0)
    clean = preprocessor(signal)
    result = detector.run(clean)
    metrics = compute_metrics(clean, clean.annotation, result.annotation, Fiducials.R_PEAK)

    results.append(metrics.to_dict())

results_df = pd.DataFrame(results)

TP = np.sum(results_df["TP"])
FP = np.sum(results_df["FP"])
FN = np.sum(results_df["FN"])

sensitivity = TP / (TP + FN) if (TP + FN) > 0 else 0
ppv = TP / (TP + FP) if (TP + FP) > 0 else 0
F1_score = (2 * ppv * sensitivity / (ppv + sensitivity) if (ppv + sensitivity) > 0 else 0)

print(f"Sensitivity (Recall): {sensitivity:.4f}")
print(f"PPV (Precision):      {ppv:.4f}")
print(f"F1-score:             {F1_score:.4f}")

results_df

Sensitivity (Recall): 0.9717
PPV (Precision):      0.9962
F1-score:             0.9838

,Symbol,Reference,Predicted,TP,FP,FN,Sensitivity,Positive Predictive Value,F1 Score,Detection Error Rate,Mean Absolute Timing Error,Mean Absolute Timing Error Std,Mean Timing Error,Timing Error Std
0,R,2273,2272,2272,0,1,0.999560,1.000000,0.999780,0.000440,0.151604,0.630982,-0.124707,0.636844
1,R,1865,1864,1863,1,2,0.998928,0.999464,0.999195,0.001609,1.016878,1.338141,1.016878,1.338141
2,R,2187,2187,2175,12,12,0.994513,0.994513,0.994513,0.010974,25.117497,13.050984,23.653895,15.547028
3,R,2084,2078,2078,0,6,0.997121,1.000000,0.998558,0.002879,0.224575,0.757222,-0.195166,0.765330
4,R,2229,2042,2020,22,209,0.906236,0.989226,0.945914,0.103634,9.786854,14.738314,8.142189,15.706850
5,R,2572,2588,2545,43,27,0.989502,0.983385,0.986434,0.027216,0.813141,3.150076,0.479153,3.217855
6,R,2027,1972,1972,0,55,0.972866,1.000000,0.986247,0.027134,3.572233,10.947332,2.811584,11.166912
7,R,2137,2124,2123,1,14,0.993449,0.999529,0.996480,0.007019,4.606950,1.767355,4.520595,1.977817
8,R,1763,1756,1746,10,17,0.990357,0.994305,0.992327,0.015315,10.175640,15.763743,-9.195622,16.354809
9,R,2532,2525,2524,1,8,0.996840,0.999604,0.998220,0.003555,1.192992,3.368860,-0.906850,3.456887
10,R,2124,2121,2120,1,4,0.998117,0.999529,0.998822,0.002354,7.862945,14.189643,4.941038,15.451797
11,R,2539,2539,2539,0,0,1.000000,1.000000,1.000000,0.000000,1.633408,1.814244,-1.548072,1.887584
12,R,1795,1794,1794,0,1,0.999443,1.000000,0.999721,0.000557,0.560510,1.114810,-0.560510,1.114810
13,R,1879,1088,1085,3,794,0.577435,0.997243,0.731378,0.424162,14.080901,16.273703,13.220686,16.979949
14,R,1953,1953,1953,0,0,1.000000,1.000000,1.000000,0.000000,1.335552,1.387864,-1.335552,1.387864
15,R,2412,2385,2384,1,28,0.988391,0.999581,0.993955,0.012023,0.588413,1.220213,-0.579092,1.224665
16,R,1535,1535,1535,0,0,1.000000,1.000000,1.000000,0.000000,16.436844,9.139301,-12.716250,13.856177
17,R,2278,2278,2278,0,0,1.000000,1.000000,1.000000,0.000000,10.341674,16.640654,6.922495,18.328684
18,R,1987,1987,1987,0,0,1.000000,1.000000,1.000000,0.000000,2.088576,4.032120,2.007493,4.073096
19,R,1863,1861,1861,0,2,0.998926,1.000000,0.999463,0.001074,0.453758,1.026910,-0.265688,1.090803
20,R,2476,2476,2476,0,0,1.000000,1.000000,1.000000,0.000000,0.160429,0.647996,0.023560,0.667144
21,R,1518,1515,1515,0,3,0.998024,1.000000,0.999011,0.001976,1.470480,1.386490,-1.470480,1.386490
22,R,1619,1585,1585,0,34,0.978999,1.000000,0.989388,0.021001,0.271644,0.848364,-0.120925,0.882547
23,R,2601,2598,2595,3,6,0.997693,0.998845,0.998269,0.003460,1.462214,2.521903,0.055663,2.914612
24,R,1963,1893,1889,4,74,0.962303,0.997887,0.979772,0.039735,4.751191,12.473888,3.992412,12.737047
25,R,2136,2115,2113,2,23,0.989232,0.999054,0.994119,0.011704,0.433822,2.128332,-0.244518,2.158289
26,R,2980,2791,2779,12,201,0.932550,0.995700,0.963091,0.071477,1.843189,5.091472,-0.217904,5.410448
27,R,2656,2652,2652,0,4,0.998494,1.000000,0.999246,0.001506,0.250335,0.838174,0.017806,0.874578
28,R,1860,1983,1795,188,65,0.965054,0.905194,0.934166,0.136022,1.459301,2.405042,0.902197,2.664550
29,R,2955,2468,2425,43,530,0.820643,0.982577,0.894339,0.193909,6.507446,12.918104,5.320733,13.450430
30,R,3005,3006,3005,1,0,1.000000,0.999667,0.999834,0.000333,1.112960,1.501147,-1.087077,1.519995
31,R,2650,2550,2548,2,102,0.961509,0.999216,0.980000,0.039245,0.462236,2.340833,-0.082854,2.384596
32,R,2748,2748,2748,0,0,1.000000,1.000000,1.000000,0.000000,0.712639,1.213136,-0.712639,1.213136
33,R,3251,3243,3213,30,38,0.988311,0.990749,0.989529,0.020917,0.887886,2.271607,-0.531694,2.380302
34,R,2262,2254,2250,4,12,0.994695,0.998225,0.996457,0.007073,0.634568,2.979456,-0.269136,3.034370
35,R,3363,3360,3360,0,3,0.999108,1.000000,0.999554,0.000892,1.510417,1.411497,-1.507110,1.415027
36,R,2208,2200,2184,16,24,0.989130,0.992727,0.990926,0.018116,9.273250,5.662928,-8.571174,6.678090
37,R,2154,2150,2150,0,4,0.998143,1.000000,0.999071,0.001857,0.466408,2.257779,-0.326873,2.282160
38,R,2048,2048,2048,0,0,1.000000,1.000000,1.000000,0.000000,1.148817,1.370735,-1.143392,1.375263
39,R,2427,2400,2400,0,27,0.988875,1.000000,0.994406,0.011125,0.481481,1.315043,-0.428241,1.333331
40,R,2483,2441,2436,5,47,0.981071,0.997952,0.989439,0.020942,2.955665,9.600756,-1.334154,9.956430
41,R,2605,2589,2589,0,16,0.993858,1.000000,0.996920,0.006142,1.522467,3.095564,-1.033217,3.291334
42,R,2053,1366,1361,5,692,0.662932,0.996340,0.796139,0.339503,1.455221,4.643641,-0.581680,4.831430
43,R,2256,2256,2256,0,0,1.000000,1.000000,1.000000,0.000000,2.242169,1.510536,-2.178142,1.601480
44,R,1571,1571,1571,0,0,1.000000,1.000000,1.000000,0.000000,0.318269,0.884751,-0.173280,0.924150
45,R,1780,1779,1779,0,1,0.999438,1.000000,0.999719,0.000562,2.549810,4.752759,-1.260071,5.244279
46,R,3079,3067,3067,0,12,0.996103,1.000000,0.998048,0.003897,2.944426,9.297110,2.123863,9.518146
47,R,2753,2749,2749,0,4,0.998547,1.000000,0.999273,0.001453,0.130350,0.587446,-0.027283,0.601116

In [4]:
detector = build_detector("wavelet")

results = []
for record_name in loader.list_records():
    record = loader[record_name]
    signal = record.get_signal(0)
    clean = preprocessor(signal)
    result = detector.run(clean)
    metrics = compute_metrics(clean, clean.annotation, result.annotation, Fiducials.R_PEAK, tolerance_ms=150)

    results.append(metrics.to_dict())

results_df = pd.DataFrame(results)

TP = np.sum(results_df["TP"])
FP = np.sum(results_df["FP"])
FN = np.sum(results_df["FN"])

sensitivity = TP / (TP + FN) if (TP + FN) > 0 else 0
ppv = TP / (TP + FP) if (TP + FP) > 0 else 0
F1_score = (2 * ppv * sensitivity / (ppv + sensitivity) if (ppv + sensitivity) > 0 else 0)

print(f"Sensitivity (Recall): {sensitivity:.4f}")
print(f"PPV (Precision):      {ppv:.4f}")
print(f"F1-score:             {F1_score:.4f}")

results_df

Sensitivity (Recall): 0.9976
PPV (Precision):      0.8889
F1-score:             0.9401

,Symbol,Reference,Predicted,TP,FP,FN,Sensitivity,Positive Predictive Value,F1 Score,Detection Error Rate,Mean Absolute Timing Error,Mean Absolute Timing Error Std,Mean Timing Error,Timing Error Std
0,R,2273,2274,2273,1,0,1.000000,0.999560,0.999780,0.000440,0.708804,5.168746,-0.058660,5.216790
1,R,1865,1877,1865,12,0,1.000000,0.993607,0.996793,0.006434,1.903485,2.956175,-1.903485,2.956175
2,R,2187,2197,2187,10,0,1.000000,0.995448,0.997719,0.004572,2.958136,10.615300,-2.851445,10.644455
3,R,2084,2085,2084,1,0,1.000000,0.999520,0.999760,0.000480,0.806409,1.260845,0.806409,1.260845
4,R,2229,2240,2228,12,1,0.999551,0.994643,0.997091,0.005832,5.599192,10.353171,-4.252693,10.975140
5,R,2572,2678,2565,113,7,0.997278,0.957804,0.977143,0.046656,15.740741,33.498526,-14.766082,33.939431
6,R,2027,2827,2026,801,1,0.999507,0.716661,0.834775,0.395659,3.830756,12.138348,-2.330811,12.513253
7,R,2137,2453,2130,323,7,0.996724,0.868325,0.928105,0.154422,6.653625,6.564917,-6.640584,6.578108
8,R,1763,2112,1593,519,170,0.903573,0.754261,0.822194,0.390811,41.126107,47.526228,-32.874730,53.566325
9,R,2532,2532,2532,0,0,1.000000,1.000000,1.000000,0.000000,2.654906,4.631509,-2.378445,4.779373
10,R,2124,4242,2122,2120,2,0.999058,0.500236,0.666667,0.999058,25.689863,19.459597,-25.535396,19.661854
11,R,2539,2546,2539,7,0,1.000000,0.997251,0.998623,0.002757,5.005251,17.137862,-1.642160,17.778137
12,R,1795,1903,1794,109,1,0.999443,0.942722,0.970254,0.061281,0.579091,1.128379,0.579091,1.128379
13,R,1879,3467,1879,1588,0,1.000000,0.541967,0.702955,0.845130,15.804802,11.380976,-3.457809,19.166688
14,R,1953,1953,1953,0,0,1.000000,1.000000,1.000000,0.000000,2.672527,0.650783,2.672527,0.650783
15,R,2412,2418,2405,13,7,0.997098,0.994624,0.995859,0.008292,3.221298,6.829715,2.197967,7.224314
16,R,1535,3069,1535,1534,0,1.000000,0.500163,0.666811,0.999349,8.208469,6.745484,2.186030,10.397201
17,R,2278,2281,2278,3,0,1.000000,0.998685,0.999342,0.001317,3.766706,3.358617,3.369183,3.757258
18,R,1987,2373,1987,386,0,1.000000,0.837337,0.911468,0.194263,36.248113,48.850431,-33.496896,50.776454
19,R,1863,1865,1863,2,0,1.000000,0.998928,0.999464,0.001074,4.435797,15.042349,-2.437824,15.492113
20,R,2476,2476,2475,1,1,0.999596,0.999596,0.999596,0.000808,2.815937,2.447563,2.730640,2.542375
21,R,1518,1533,1518,15,0,1.000000,0.990215,0.995084,0.009881,9.186064,23.804017,0.501391,25.510068
22,R,1619,1625,1619,6,0,1.000000,0.996308,0.998150,0.003706,1.612793,3.859976,-0.988264,4.064954
23,R,2601,2632,2600,32,1,0.999616,0.987842,0.993694,0.012687,4.210470,7.371758,1.214744,8.402099
24,R,1963,2697,1963,734,0,1.000000,0.727846,0.842489,0.373917,5.685742,16.409461,-0.939605,17.341143
25,R,2136,2412,2135,277,1,0.999532,0.885158,0.938874,0.130150,1.774655,3.661019,1.608119,3.737167
26,R,2980,3148,2950,198,30,0.989933,0.937103,0.962794,0.076510,4.536723,13.818952,-2.237288,14.371494
27,R,2656,2685,2655,30,1,0.999623,0.988827,0.994196,0.011672,0.689475,3.497654,0.411174,3.541171
28,R,1860,2241,1855,386,5,0.997312,0.827755,0.904657,0.210215,2.984426,10.050812,-1.322252,10.400831
29,R,2955,2987,2951,36,4,0.998646,0.987948,0.993268,0.013536,4.859934,9.096736,2.444557,10.019666
30,R,3005,3038,3003,35,2,0.999334,0.988479,0.993877,0.012313,2.609428,7.328998,1.547527,7.624204
31,R,2650,2699,2648,51,2,0.999245,0.981104,0.990092,0.020000,1.593446,4.756322,0.557024,4.985117
32,R,2748,2822,2748,74,0,1.000000,0.973777,0.986715,0.026929,20.440118,28.304878,-8.552685,33.849906
33,R,3251,3257,3250,7,1,0.999692,0.997851,0.998771,0.002461,2.274359,10.031794,-0.595726,10.269114
34,R,2262,2388,2261,127,1,0.999558,0.946817,0.972473,0.056587,2.544351,4.059965,2.195440,4.258766
35,R,3363,3374,3363,11,0,1.000000,0.996740,0.998367,0.003271,2.466383,3.094173,2.284666,3.230673
36,R,2208,2647,2206,441,2,0.999094,0.833396,0.908754,0.200634,16.100030,9.069010,-14.931500,10.886149
37,R,2154,2325,2154,171,0,1.000000,0.926452,0.961822,0.079387,2.197462,4.362176,0.918188,4.797328
38,R,2048,2048,2048,0,0,1.000000,1.000000,1.000000,0.000000,2.903917,2.105618,2.789985,2.254406
39,R,2427,2483,2427,56,0,1.000000,0.977447,0.988595,0.023074,1.779746,3.601002,1.408918,3.761604
40,R,2483,2751,2467,284,16,0.993556,0.896765,0.942682,0.120822,9.086610,23.986640,-8.037202,24.358340
41,R,2605,2631,2604,27,1,0.999616,0.989738,0.994652,0.010749,3.670635,5.008587,1.876387,5.919348
42,R,2053,2500,2053,447,0,1.000000,0.821200,0.901823,0.217730,10.697083,19.246609,-9.484765,19.872061
43,R,2256,2261,2256,5,0,1.000000,0.997789,0.998893,0.002216,3.222271,4.314758,2.929226,4.518828
44,R,1571,2185,1571,614,0,1.000000,0.718993,0.836528,0.390834,10.051984,25.804496,-7.739232,26.589823
45,R,1780,3817,1780,2037,0,1.000000,0.466335,0.636055,1.144382,2.339263,2.830829,2.298689,2.863874
46,R,3079,3080,3079,1,0,1.000000,0.999675,0.999838,0.000325,6.182563,12.863635,-2.332106,14.080429
47,R,2753,2754,2753,1,0,1.000000,0.999637,0.999818,0.000363,0.627598,2.341099,0.490374,2.373638